<?php

namespace App\Services;

use App\Models\SalesInvoice;
use App\Models\SalesInvoiceItem;
use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Csv as CsvWriter;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx as XlsxWriter;
use Workdo\Account\Models\Customer;
use Workdo\ProductService\Models\ProductServiceItem;

/**
 * SALES INVOICE IMPORT / EXPORT
 * =============================================================================
 * Built on phpoffice/phpspreadsheet, already a dependency — nothing new to
 * install. Follows the same shape as CustomerImportExportService so the two
 * behave consistently.
 *
 * WHY INVOICES ARE HARDER THAN CUSTOMERS
 *
 * A customer is one row. An invoice is a header PLUS a variable number of line
 * items, and a spreadsheet is flat. The format used here is the one accountants
 * already recognise from every other system:
 *
 *     ONE ROW PER LINE ITEM. Rows sharing an Invoice Number belong to the same
 *     invoice. Header fields are read from the FIRST row of each group; on
 *     subsequent rows they may be left blank.
 *
 *     Invoice No | Customer | Date       | Due        | Item      | Qty | Price
 *     INV-001    | Acme     | 2026-01-05 | 2026-02-05 | Widget    |  10 | 25.00
 *               |          |            |            | Fitting   |   2 | 40.00
 *     INV-002    | Najd     | 2026-01-06 | 2026-02-06 | Widget    |   1 | 25.00
 *
 * TOTALS ARE NEVER IMPORTED. Subtotal, tax and total are recalculated from the
 * lines. A spreadsheet total that disagrees with its own lines is a common and
 * dangerous error; trusting it would put a wrong figure into the ledger.
 *
 * IMPORTS ARE ALWAYS CREATED AS DRAFT. No journal entries are generated by the
 * import. An imported batch is reviewed and posted through the normal workflow,
 * so the accounting entry is raised by the same code path as a manual invoice
 * and nothing reaches the ledger without a human posting it.
 *
 * VALIDATION IS ALL-OR-NOTHING. Every row is checked before anything is
 * written, and the write runs in a transaction. A file with errors imports
 * nothing — you never end up with half a batch loaded and no clean way back.
 */
class SalesInvoiceImportExportService
{
    /** Sheet columns, in order. Shared by export, template and importer. */
    public const COLUMNS = [
        'invoice_number'   => 'Invoice Number',
        'customer_code'    => 'Customer Code',
        'customer_name'    => 'Customer Name',
        'invoice_date'     => 'Invoice Date',
        'due_date'         => 'Due Date',
        'payment_terms'    => 'Payment Terms',
        'item_sku'         => 'Item SKU',
        'item_name'        => 'Item Name',
        'description'      => 'Line Description',
        'quantity'         => 'Quantity',
        'unit_price'       => 'Unit Price',
        'discount_percent' => 'Discount %',
        'tax_percent'      => 'VAT %',
        'line_total'       => 'Line Total',
        'status'           => 'Status',
        'notes'            => 'Notes',
    ];

    // =================================================================
    // Export
    // =================================================================

    /**
     * Export invoices matching the caller's current filters.
     *
     * The filter array is the same one the index screen uses, so what is
     * exported is exactly what the user is looking at. Exporting the whole
     * table regardless of filters is a common and infuriating bug — the user
     * filters to 12 overdue invoices, clicks Export, and gets 4,000 rows.
     *
     * @param  array{customer_id?:mixed,status?:string,search?:string,date_range?:string}  $filters
     * @param  'xlsx'|'csv'  $format
     */
    public function export(array $filters = [], string $format = 'xlsx'): string
    {
        $query = SalesInvoice::query()
            ->with(['customer', 'items.product'])
            ->where(function ($q) {
                if (Auth::user()->can('manage-any-sales-invoices')) {
                    $q->where('created_by', creatorId());
                } elseif (Auth::user()->can('manage-own-sales-invoices')) {
                    $q->where('creator_id', Auth::id())->orWhere('customer_id', Auth::id());
                } else {
                    $q->whereRaw('1 = 0');
                }
            });

        if (!empty($filters['customer_id'])) {
            $query->where('customer_id', $filters['customer_id']);
        }

        if (!empty($filters['search'])) {
            $query->where('invoice_number', 'like', '%' . $filters['search'] . '%');
        }

        if (!empty($filters['status'])) {
            // "overdue" is a derived state, not a stored one — an invoice
            // becomes overdue by the passage of time and nothing rewrites its
            // status when the date passes. It has to be computed here or the
            // export silently returns nothing.
            if ($filters['status'] === 'overdue') {
                $query->whereNotIn('status', ['draft', 'cancelled', 'paid'])
                      ->where('balance_amount', '>', 0)
                      ->whereDate('due_date', '<', now());
            } else {
                $query->where('status', $filters['status']);
            }
        }

        if (!empty($filters['date_range']) && str_contains($filters['date_range'], ' - ')) {
            [$from, $to] = explode(' - ', $filters['date_range']);
            $query->whereBetween('invoice_date', [
                Carbon::parse($from)->startOfDay(),
                Carbon::parse($to)->endOfDay(),
            ]);
        }

        $rows = [];

        foreach ($query->orderBy('invoice_date')->orderBy('id')->get() as $invoice) {
            $items = $invoice->items;

            // An invoice with no lines still exports one row, or it would
            // vanish from the export entirely and look like data loss.
            if ($items->isEmpty()) {
                $rows[] = array_merge($this->headerRow($invoice), array_fill(0, 10, ''));
                continue;
            }

            $first = true;
            foreach ($items as $item) {
                $rows[] = array_values(array_merge(
                    // Header fields repeat on every line. Repetition beats
                    // blanks here: a filtered or sorted export must stay
                    // readable row by row.
                    $this->headerRow($invoice),
                    [
                        $item->product->sku ?? '',
                        $item->product->name ?? '',
                        '', // sales_invoice_items has no description column
                        $item->quantity,
                        $item->unit_price,
                        $item->discount_percentage ?? 0,
                        $item->tax_percentage ?? 0,
                        $item->total_amount,
                        $first ? $invoice->status : '',
                        $first ? ($invoice->notes ?? '') : '',
                    ]
                ));
                $first = false;
            }
        }

        return $this->writeSheet($rows, 'sales-invoices', $format);
    }

    /** Header columns for one invoice, repeated on each of its lines. */
    private function headerRow(SalesInvoice $invoice): array
    {
        return [
            $invoice->invoice_number,
            $invoice->customerDetails->customer_code ?? '',
            $invoice->customer->name ?? '',
            optional($invoice->invoice_date)->format('Y-m-d'),
            optional($invoice->due_date)->format('Y-m-d'),
            $invoice->payment_terms ?? '',
        ];
    }

    /** A template with two example invoices showing the grouping convention. */
    public function template(): string
    {
        $rows = [
            ['INV-EXAMPLE-1', 'CUST-0001', 'Acme Trading LLC', '2026-01-05', '2026-02-05', 'Net 30',
             'SKU-001', 'Steel bracket', 'Galvanised, 40mm', 10, 25.00, 0, 15, 250.00, 'draft', 'Example — delete before importing'],
            ['', '', '', '', '', '',
             'SKU-002', 'Fitting kit', '', 2, 40.00, 5, 15, 76.00, '', ''],
            ['INV-EXAMPLE-2', 'CUST-0002', 'Najd Contracting', '2026-01-06', '2026-02-06', 'Net 15',
             'SKU-001', 'Steel bracket', '', 1, 25.00, 0, 15, 25.00, 'draft', ''],
        ];

        return $this->writeSheet($rows, 'sales-invoices-template', 'xlsx');
    }

    // =================================================================
    // Import
    // =================================================================

    /**
     * Validate an uploaded sheet WITHOUT writing anything.
     *
     * The specification asks for a preview before posting and per-row error
     * reporting. This is that step: it returns exactly what would be created,
     * plus every problem found, so the user confirms against real numbers
     * rather than hoping.
     *
     * @return array{invoices:array, errors:array, duplicates:array, summary:array}
     */
    public function preview(string $path): array
    {
        return $this->analyse($path);
    }

    /**
     * Commit a previously previewed file.
     *
     * Re-runs the full analysis rather than trusting anything passed back from
     * the browser. The file is the source of truth; a client-side payload is
     * not, and re-reading costs milliseconds.
     */
    public function import(string $path): array
    {
        $result = $this->analyse($path);

        if (!empty($result['errors'])) {
            return [
                'imported' => 0,
                'errors'   => $result['errors'],
                'message'  => __('Nothing was imported — fix the errors and try again.'),
            ];
        }

        $created = 0;

        DB::transaction(function () use ($result, &$created) {
            foreach ($result['invoices'] as $draft) {
                $invoice = SalesInvoice::create([
                    'invoice_number'  => $draft['invoice_number'],
                    'invoice_date'    => $draft['invoice_date'],
                    'due_date'        => $draft['due_date'],
                    'customer_id'     => $draft['customer_id'],
                    'payment_terms'   => $draft['payment_terms'],
                    'subtotal'        => $draft['subtotal'],
                    'discount_amount' => $draft['discount_amount'],
                    'tax_amount'      => $draft['tax_amount'],
                    'total_amount'    => $draft['total_amount'],
                    'paid_amount'     => 0,
                    'balance_amount'  => $draft['total_amount'],
                    // ALWAYS draft. No journal entry is raised by the import;
                    // posting goes through the normal workflow so the ledger
                    // entry comes from the same code path as a manual invoice.
                    'status'          => 'draft',
                    'type'            => 'product',
                    'notes'           => $draft['notes'],
                    'creator_id'      => Auth::id(),
                    'created_by'      => creatorId(),
                ]);

                foreach ($draft['items'] as $line) {
                    SalesInvoiceItem::create([
                        'invoice_id'          => $invoice->id,
                        'product_id'          => $line['product_id'],
                        'quantity'            => $line['quantity'],
                        'unit_price'          => $line['unit_price'],
                        'discount_percentage' => $line['discount_percent'],
                        'discount_amount'     => $line['discount_amount'],
                        'tax_percentage'      => $line['tax_percent'],
                        'tax_amount'          => $line['tax_amount'],
                        'total_amount'        => $line['total'],
                        'creator_id'          => Auth::id(),
                        'created_by'          => creatorId(),
                    ]);
                }

                $created++;
            }
        });

        return [
            'imported' => $created,
            'errors'   => [],
            'message'  => trans_choice(
                '{1} :count invoice imported as draft.|[2,*] :count invoices imported as drafts.',
                $created,
                ['count' => $created]
            ),
        ];
    }

    /**
     * Read, group and validate the sheet. Shared by preview() and import() so
     * the two can never disagree about what a file means.
     */
    private function analyse(string $path): array
    {
        $sheet = IOFactory::load($path)->getActiveSheet();
        $raw = $sheet->toArray(null, true, true, false);

        if (count($raw) < 2) {
            return [
                'invoices'   => [],
                'errors'     => [__('The file has no data rows.')],
                'duplicates' => [],
                'summary'    => [],
            ];
        }

        array_shift($raw); // header

        $keys = array_keys(self::COLUMNS);
        $errors = [];
        $duplicates = [];
        $groups = [];
        $currentNumber = null;

        // Look-ups resolved once. A per-row query on a 2,000-line sheet is
        // 2,000 queries.
        $customersByCode = Customer::where('created_by', creatorId())
            ->pluck('user_id', 'customer_code');
        $customersByName = Customer::where('created_by', creatorId())
            ->pluck('user_id', 'company_name');
        $productsBySku = ProductServiceItem::where('created_by', creatorId())
            ->whereNotNull('sku')->pluck('id', 'sku');
        $productsByName = ProductServiceItem::where('created_by', creatorId())
            ->pluck('id', 'name');

        $existingNumbers = SalesInvoice::where('created_by', creatorId())
            ->pluck('invoice_number')->flip();

        foreach ($raw as $index => $row) {
            $lineNo = $index + 2; // +1 for the header, +1 for 1-based rows

            if (count(array_filter($row, fn ($v) => $v !== null && $v !== '')) === 0) {
                continue; // blank spacer row
            }

            $values = [];
            foreach ($keys as $position => $key) {
                $values[$key] = isset($row[$position]) ? trim((string) $row[$position]) : '';
            }

            // A row with an invoice number starts a new invoice; a row without
            // one continues the previous invoice.
            if ($values['invoice_number'] !== '') {
                $currentNumber = $values['invoice_number'];

                if (isset($existingNumbers[$currentNumber])) {
                    $duplicates[] = __('Row :row: invoice :number already exists and was skipped.', [
                        'row' => $lineNo, 'number' => $currentNumber,
                    ]);
                    $currentNumber = null;
                    continue;
                }

                if (!isset($groups[$currentNumber])) {
                    $customerId = $this->resolveCustomer($values, $customersByCode, $customersByName);

                    if (!$customerId) {
                        $errors[] = __('Row :row: customer ":name" was not found.', [
                            'row'  => $lineNo,
                            'name' => $values['customer_name'] ?: $values['customer_code'],
                        ]);
                    }

                    if ($values['invoice_date'] === '') {
                        $errors[] = __('Row :row: invoice date is required.', ['row' => $lineNo]);
                    }

                    $groups[$currentNumber] = [
                        'invoice_number' => $currentNumber,
                        'customer_id'    => $customerId,
                        'customer_name'  => $values['customer_name'],
                        'invoice_date'   => $this->parseDate($values['invoice_date']),
                        'due_date'       => $this->parseDate($values['due_date']),
                        'payment_terms'  => $values['payment_terms'] ?: null,
                        'notes'          => $values['notes'] ?: null,
                        'items'          => [],
                        'first_row'      => $lineNo,
                    ];
                }
            }

            if ($currentNumber === null) {
                // Continuation of a skipped duplicate, or a line before any
                // invoice number was given.
                if ($values['item_name'] !== '' || $values['item_sku'] !== '') {
                    $errors[] = __('Row :row: line item has no invoice number above it.', ['row' => $lineNo]);
                }
                continue;
            }

            if ($values['item_name'] === '' && $values['item_sku'] === '') {
                continue; // header-only row, no line on it
            }

            $productId = $this->resolveProduct($values, $productsBySku, $productsByName);
            if (!$productId) {
                $errors[] = __('Row :row: item ":name" was not found in the catalogue.', [
                    'row'  => $lineNo,
                    'name' => $values['item_name'] ?: $values['item_sku'],
                ]);
            }

            $qty = (float) str_replace(',', '', $values['quantity']);
            $price = (float) str_replace(',', '', $values['unit_price']);

            if ($qty <= 0) {
                $errors[] = __('Row :row: quantity must be greater than zero.', ['row' => $lineNo]);
            }
            if ($price < 0) {
                $errors[] = __('Row :row: unit price cannot be negative.', ['row' => $lineNo]);
            }

            $discountPercent = (float) $values['discount_percent'];
            $taxPercent = (float) $values['tax_percent'];

            // Recomputed from quantity and price — the sheet's own Line Total
            // column is exported for readability and ignored on import.
            $gross = $qty * $price;
            $discountAmount = round($gross * ($discountPercent / 100), 2);
            $net = $gross - $discountAmount;
            $taxAmount = round($net * ($taxPercent / 100), 2);

            $groups[$currentNumber]['items'][] = [
                'product_id'       => $productId,
                'description'      => $values['description'] ?: null,
                'quantity'         => $qty,
                'unit_price'       => $price,
                'discount_percent' => $discountPercent,
                'discount_amount'  => $discountAmount,
                'tax_percent'      => $taxPercent,
                'tax_amount'       => $taxAmount,
                'total'            => round($net + $taxAmount, 2),
                'row'              => $lineNo,
            ];
        }

        // Totals, and a final check that every invoice actually has lines.
        $invoices = [];
        foreach ($groups as $number => $group) {
            if (empty($group['items'])) {
                $errors[] = __('Invoice :number (row :row) has no line items.', [
                    'number' => $number, 'row' => $group['first_row'],
                ]);
                continue;
            }

            $subtotal = 0;
            $discount = 0;
            $tax = 0;
            $total = 0;

            foreach ($group['items'] as $item) {
                $subtotal += $item['quantity'] * $item['unit_price'];
                $discount += $item['discount_amount'];
                $tax      += $item['tax_amount'];
                $total    += $item['total'];
            }

            $group['subtotal']        = round($subtotal, 2);
            $group['discount_amount'] = round($discount, 2);
            $group['tax_amount']      = round($tax, 2);
            $group['total_amount']    = round($total, 2);
            $group['line_count']      = count($group['items']);

            $invoices[] = $group;
        }

        return [
            'invoices'   => $invoices,
            'errors'     => $errors,
            'duplicates' => $duplicates,
            'summary'    => [
                'invoice_count' => count($invoices),
                'line_count'    => array_sum(array_column($invoices, 'line_count')),
                'total_value'   => round(array_sum(array_column($invoices, 'total_amount')), 2),
                'error_count'   => count($errors),
                'skipped_count' => count($duplicates),
            ],
        ];
    }

    /** Customer code first — it is unique; names are not. */
    private function resolveCustomer(array $values, $byCode, $byName): ?int
    {
        if ($values['customer_code'] !== '' && isset($byCode[$values['customer_code']])) {
            return (int) $byCode[$values['customer_code']];
        }
        if ($values['customer_name'] !== '' && isset($byName[$values['customer_name']])) {
            return (int) $byName[$values['customer_name']];
        }
        return null;
    }

    /** SKU first, for the same reason. */
    private function resolveProduct(array $values, $bySku, $byName): ?int
    {
        if ($values['item_sku'] !== '' && isset($bySku[$values['item_sku']])) {
            return (int) $bySku[$values['item_sku']];
        }
        if ($values['item_name'] !== '' && isset($byName[$values['item_name']])) {
            return (int) $byName[$values['item_name']];
        }
        return null;
    }

    /**
     * Accepts what people actually type, plus Excel's numeric serial dates —
     * a date-formatted cell arrives as 45678, not as text.
     */
    private function parseDate(string $value): ?string
    {
        if ($value === '') {
            return null;
        }

        if (is_numeric($value)) {
            try {
                return Carbon::instance(
                    \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject((float) $value)
                )->format('Y-m-d');
            } catch (\Throwable) {
                return null;
            }
        }

        foreach (['Y-m-d', 'd/m/Y', 'd-m-Y', 'm/d/Y', 'Y/m/d'] as $format) {
            try {
                return Carbon::createFromFormat($format, $value)->format('Y-m-d');
            } catch (\Throwable) {
                continue;
            }
        }

        try {
            return Carbon::parse($value)->format('Y-m-d');
        } catch (\Throwable) {
            return null;
        }
    }

    // =================================================================
    // Writing
    // =================================================================

    private function writeSheet(array $rows, string $basename, string $format = 'xlsx'): string
    {
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Sales Invoices');

        $sheet->fromArray(array_values(self::COLUMNS), null, 'A1');

        $lastColumn = $sheet->getHighestColumn();
        $headerRange = "A1:{$lastColumn}1";

        $sheet->getStyle($headerRange)->getFont()->setBold(true);
        $sheet->getStyle($headerRange)->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()->setRGB('1E3A5F');
        $sheet->getStyle($headerRange)->getFont()->getColor()->setRGB('FFFFFF');
        $sheet->getStyle($headerRange)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        $sheet->getRowDimension(1)->setRowHeight(22);
        $sheet->freezePane('A2');

        if (!empty($rows)) {
            $sheet->fromArray($rows, null, 'A2');
        }

        foreach (range('A', $lastColumn) as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(true);
        }

        $extension = $format === 'csv' ? 'csv' : 'xlsx';
        $path = storage_path('app/' . $basename . '-' . now()->format('Ymd-His') . '.' . $extension);

        if (!is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }

        if ($format === 'csv') {
            $writer = new CsvWriter($spreadsheet);
            // UTF-8 BOM, or Excel mangles Arabic customer names on open.
            $writer->setUseBOM(true);
            $writer->save($path);
        } else {
            (new XlsxWriter($spreadsheet))->save($path);
        }

        $spreadsheet->disconnectWorksheets();

        return $path;
    }
}
